language: lisp

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    #- LISP=ccl
    #- LISP=ccl32
    #- LISP=clisp
    #- LISP=clisp32
    #- LISP=cmucl
    #- LISP=ecl

# matrix:
#   allow_failures:
#     - env: LISP=ccl32

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  - if [ "${LISP:(-2)}" = "32" ]; then
      sudo apt-get install libc6-dev-i386 libffi-dev:i386;
    fi
  - mkdir -p ~/quicklisp/dists/pauldist
  - curl -L http://pauldist.kisp.in/pauldist.txt > ~/quicklisp/dists/pauldist/distinfo.txt
  - touch  ~/quicklisp/dists/pauldist/enabled.txt
  #- git clone --depth=1 git://github.com/trivial-features/trivial-features.git ~/lisp/trivial-features
  #- git clone git://common-lisp.net/projects/alexandria/alexandria.git ~/lisp/alexandria
  #- git clone --depth=1 git://github.com/cl-babel/babel.git ~/lisp/babel
  - echo the PATH is
  - echo $PATH
  - mkdir ttt
  - curl -L http://www.minizinc.org/downloads/release-2.0.1/minizinc-2.0.1-linux64.tar.gz >ttt/minizinc-2.0.1-linux64.tar.gz
  - cd ttt; tar xfz minizinc-2.0.1-linux64.tar.gz
  - echo we are now in `pwd`
  - ls -al
  - cd minizinc-2.0.1
  - ls -al
  - cd bin
  - export PATH=`pwd`:$PATH
  
script:
  - cl -e '(ql:quickload "graph-as-mzn-input-test")
           (uiop:quit (if (myam:load-and-run! "graph-as-mzn-input-test") 0 1))'
